import json
a = {
                "creditReqNo":"20200706456123001",
                "insuranceNo":"2020070615030988245",
                "name":"隗贝光",
                "spelling":"",
                "sex":"00",
                "nationality":"中国",
                "nation":"汉族",
                "birthday":"1990/06/02",
                "idType":"00",
                "idNo":"65232519930329469X",
                "idStartDate":"2016/01/18",
                "idEndDate":"2036/01/18",
                "idOffice":"杭州市公安局江干区分局",
                "marriage":"00",
                "children":"01",
                "supplyPeople":0,
                "house":"05",
                "addProvince":"110000",
                "addCity":"110000",
                "addDistrict":"110101",
                "addDetail":"学霸路学渣小区250弄38号",
                "industry":"C",
                "profession":"00",
                "workplaceName":"大地保险公司",
                "workTel":"021-1254684",
                "workProvince":"",
                "workCity":"",
                "workDistrict":"",
                "workDetailAdd":"学院路100号小杨制造厂",
                "workAge":5,
                "income":"04",
                "education":"08",
                "school":"哈弗",
                "phone":"16607063242",
                "email":"ybhdsg@hrtx.com",
                "contacts":[
                    {
                        "relation":"00",
                        "name":"哑巴湖大水怪",
                        "phoneNo":"17613145210"
                    },
                    {
                        "relation":"00",
                        "name":"哑巴湖大水怪",
                        "phoneNo":"17613145210"
                    }
                ],
                "bankCard":"6226661203661652",
                "bankName":"工商银行",
                "bankPhone":"13784566444",
                "applyProvince":"110000",
                "applyCity":"110000",
                "applyDistrict":"110101",
                "applyResult":"99",
                "loanAmount":5000,
                "periods":3,
                "purpose":"01",
                "direction":"00",
                "payType":"00",
                "payMerchantNo":"",
                "authFlag":"01",
                "deviceDetail":{
                    "deviceId":"",
                    "mac":"",
                    "longitude":"",
                    "latitude":"",
                    "gpsCity":"",
                    "ip":"",
                    "ipCity":"",
                    "oS":""
                },
                "docDate":"2020/07/06",
                "channelDetail":{
                    "childProductId":"01",
                    "bankLimit":"30000",
                    "billAge":"36",
                    "insuranceName":"BCM",
                    "insuranceAdd":"BCM",
                    "postCode":"110016"
                }
            }
print(type(a))
a = json.dumps(a)
print(type(a))

