# -*- coding: utf-8 -*-

# import unittest
# from test_mathfunc import TestMathFunc
# from HTMLTestRunner import HTMLTestRunner
#
# if __name__ == '__main__':
#     #容器   测试套件
#     suite = unittest.TestSuite()
#     #将用例放到容器里
#     suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))
#     #生成HTML测试报告
#     with open('HTMLReport.html', 'wb') as f:
#         runner = HTMLTestRunner(stream=f,
#                                 title='MathFunc Test Report',
#                                 description='generated by HTMLTestRunner.',
#                                 verbosity=2
#                                 )
#         runner.run(suite)
import os
import unittest
from test_mathfunc import TestMathFunc
from HTMLTestRunner import HTMLTestRunner

if __name__ == '__main__':
    suite = unittest.TestSuite()

    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestMathFunc))

    with open(os.path.join(os.path.dirname(__file__),'HTMLReport.html'),'wb') as f:
        runner = HTMLTestRunner(stream=f,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)