# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/demo_testcase_110.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseDemoTestcase110(HttpRunner):

    config = Config("request methods testcase: reference testcase").base_url(
        "${ENV(URL)}"
    )

    teststeps = [
        Step(
            RunRequest("post form data")
            .post("/queryAmount")
            .with_data({"pas": "${bankcard()}"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseDemoTestcase110().test_start()
