# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/test.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseTest(HttpRunner):

    config = Config("request methods testcase: reference testcase").base_url(
        "https://www.baidu.com"
    )

    teststeps = [
        Step(
            RunRequest("post form data")
            .get("/")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseTest().test_start()
